parameters:
  path: data/wine-quality.csv
  repo: https://github.com/kasyap324/CI_DVC_MLFlow_CML.git
  version: experiment
<<<<<<< HEAD
  alpha: 0.5
=======
  alpha: 0.5
>>>>>>> c04a0a6a31c2903fb8c9e2467f776cc2551e6453
  l1_ratio: 0.5000
