name: CML & DVC
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Train model
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE }}
        run: |
          pip install -r requirements.txt  # Install dependencies
          dvc pull --run-cache        # Pull data & run-cache from S3
          dvc repro 
